spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: 1234546
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.techdevhub.user.entity
  configuration:
    map-underscore-to-camel-case: true
techdevhub:
  jwt:
    secret-key: TechDevHubDefaultSecretKeyForJwtAuth2026
    expiration: 86400000
    issuer: techdevhub
    header-name: Authorization
    token-prefix: "Bearer "
    exclude-paths:
      - /users/register
      - /users/login
      - /error
      - /swagger-ui/**
      - /v3/api-docs/**
server:
  port: 8081