spring:
  application:
    name: gateway-service

  cloud:
    nacos:
      server-addr: 127.0.0.1:8848

    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/users/**

            - id: blog-service
              uri: lb://blog-service
              predicates:
                - Path=/blogs/**

            - id: category-service
              uri: lb://category-service
              predicates:
                - Path=/categories/**

            - id: follow-service
              uri: lb://follow-service
              predicates:
                - Path=/follows/**

            - id: like-service
              uri: lb://like-service
              predicates:
                - Path=/likes/**

            - id: comment-service
              uri: lb://comment-service
              predicates:
                - Path=/comments/**

            - id: ai-service
              uri: lb://ai-service
              predicates:
                - Path=/ai/**

server:
  port: 8090